name: Send Pair programming message every two weeks

on:
  schedule:
    - cron: '0 */336 * * 1'
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # pin@v2
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --immutable
      - name: Build TypeScript code
        run: yarn build
      - name: Run code
        run: node dist/index.js
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          EXCLUDE_IDS: ${{ secrets.EXCLUDE_IDS }}
          TENOR_TOKEN: ${{ secrets.TENOR_TOKEN }}
